server.port=8080
spring.application.name=api-gateway

# ???????????? ??? net.devh gRPC ????????
grpc.client.trainings-service.address=localhost:50051
grpc.client.trainings-service.negotiation-type=PLAINTEXT

logging.level.net.devh.boot.grpc=DEBUG

# Jackson (JSON ????????????)
spring.jackson.property-naming-strategy=SNAKE_CASE