server.port=8080
spring.application.name=api-gateway

# ???????????? ??? net.devh gRPC ????????
# Trainings Service
grpc.client.trainings-service.address=static://localhost:50055
grpc.client.trainings-service.negotiation-type=PLAINTEXT

# Account Service
grpc.client.account-service.address=static://localhost:50052
grpc.client.account-service.negotiation-type=PLAINTEXT

# Auth Service
grpc.client.auth-service.address=static://localhost:50053
grpc.client.auth-service.negotiation-type=PLAINTEXT


logging.level.net.devh.boot.grpc=DEBUG

# Jackson (JSON ????????????)
spring.jackson.property-naming-strategy=SNAKE_CASE